# Generated by Django 6.0.6 on 2026-06-26 09:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('model_name', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=80)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('inventory_deducted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_daily_operations', to=settings.AUTH_USER_MODEL)),
                ('encoded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encoded_daily_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-operation_date', 'station__name'],
            },
        ),
        migrations.CreateModel(
            name='CashCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gcash_or_bank_transfer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('card_payments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('shortage', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('overage', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('daily_operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_collection', to='api.dailyoperation')),
            ],
            options={
                'ordering': ['-daily_operation__operation_date'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('timezone', models.CharField(default='Asia/Manila', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=30)),
                ('current_price_per_liter', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_per_liter', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_products', to='api.station')),
            ],
            options={
                'ordering': ['station__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('paid_by', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('encoded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encoded_expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='api.expensecategory')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.station')),
            ],
            options={
                'ordering': ['-expense_date', 'category__name'],
            },
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_operations', to='api.station'),
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity_liters', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_volume_liters', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reorder_level_liters', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('fuel_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanks', to='api.fuelproduct')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='api.station')),
            ],
            options={
                'ordering': ['station__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('meter_number', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('fuel_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pumps', to='api.fuelproduct')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumps', to='api.station')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pumps', to='api.tank')),
            ],
            options={
                'ordering': ['station__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_date', models.DateField()),
                ('adjustment_type', models.CharField(choices=[('gain', 'Gain'), ('loss', 'Loss'), ('correction', 'Correction')], max_length=20)),
                ('liters', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('reason', models.TextField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('encoded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encoded_inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='api.station')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='api.tank')),
            ],
            options={
                'ordering': ['-adjustment_date', 'station__name'],
            },
        ),
        migrations.CreateModel(
            name='FuelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateField()),
                ('liters_delivered', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('cost_per_liter', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_fuel_deliveries', to=settings.AUTH_USER_MODEL)),
                ('fuel_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_deliveries', to='api.fuelproduct')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_deliveries', to='api.station')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_deliveries', to='api.supplier')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_deliveries', to='api.tank')),
            ],
            options={
                'ordering': ['-delivery_date', 'station__name'],
            },
        ),
        migrations.CreateModel(
            name='PumpReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_reading', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('closing_reading', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('liters_sold', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=12)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expected_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('daily_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.dailyoperation')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='api.pump')),
            ],
            options={
                'ordering': ['daily_operation__operation_date', 'pump__name'],
                'constraints': [models.UniqueConstraint(fields=('daily_operation', 'pump'), name='unique_pump_reading_per_operation')],
            },
        ),
        migrations.AddConstraint(
            model_name='fuelproduct',
            constraint=models.UniqueConstraint(fields=('station', 'code'), name='unique_fuel_product_code_per_station'),
        ),
        migrations.AddConstraint(
            model_name='dailyoperation',
            constraint=models.UniqueConstraint(fields=('station', 'operation_date'), name='unique_daily_operation_per_station_date'),
        ),
        migrations.AddConstraint(
            model_name='tank',
            constraint=models.UniqueConstraint(fields=('station', 'name'), name='unique_tank_name_per_station'),
        ),
        migrations.AddConstraint(
            model_name='pump',
            constraint=models.UniqueConstraint(fields=('station', 'meter_number'), name='unique_pump_meter_per_station'),
        ),
    ]
