# Generated by Django 6.0.6 on 2026-06-29 02:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_station_owner_memberships(apps, schema_editor):
    Station = apps.get_model("api", "Station")
    StationMembership = apps.get_model("api", "StationMembership")

    memberships = [
        StationMembership(
            station_id=station.id,
            user_id=station.owner_id,
            role="owner",
            status="active",
        )
        for station in Station.objects.exclude(owner_id=None)
    ]
    StationMembership.objects.bulk_create(memberships, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('accountant', 'Accountant')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='station_invitations', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff'), ('accountant', 'Accountant')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_station_memberships', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['station__name', 'role', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('station', 'user'), name='unique_station_membership')],
            },
        ),
        migrations.RunPython(
            backfill_station_owner_memberships,
            migrations.RunPython.noop,
        ),
    ]
