# Generated by Django 6.0.6 on 2026-06-29 03:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_reading_costs_and_collection_variance(apps, schema_editor):
    CashCollection = apps.get_model("api", "CashCollection")
    PumpReading = apps.get_model("api", "PumpReading")

    for reading in PumpReading.objects.select_related("pump__fuel_product"):
        reading.cost_per_liter = reading.pump.fuel_product.cost_per_liter
        reading.save(update_fields=["cost_per_liter"])

    for collection in CashCollection.objects.all():
        expected_sales = (
            PumpReading.objects.filter(daily_operation_id=collection.daily_operation_id)
            .aggregate(total=models.Sum("expected_sales"))["total"]
            or Decimal("0")
        )
        total_collection = (
            collection.actual_cash
            + collection.gcash_or_bank_transfer
            + collection.card_payments
            + collection.credit_sales
        )
        variance = total_collection - expected_sales
        collection.expected_sales = expected_sales
        collection.shortage = abs(variance) if variance < 0 else Decimal("0")
        collection.overage = variance if variance > 0 else Decimal("0")
        collection.save(
            update_fields=["expected_sales", "shortage", "overage"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scope_suppliers_to_stations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyoperation',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='reopen_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reopened_daily_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pumpreading',
            name='cost_per_liter',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.RunPython(
            backfill_reading_costs_and_collection_variance,
            migrations.RunPython.noop,
        ),
    ]
