# Generated by Django 6.0.6 on 2026-06-29 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dailyoperation_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyoperation',
            name='unique_daily_operation_per_station_date',
        ),
        migrations.RemoveConstraint(
            model_name='pumpreading',
            name='unique_pump_reading_per_operation',
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fueldelivery',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fueldelivery',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fueldelivery',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fueldelivery',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pumpreading',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pumpreading',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pumpreading',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pumpreading',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='dailyoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('station', 'operation_date'), name='unique_daily_operation_per_station_date'),
        ),
        migrations.AddConstraint(
            model_name='pumpreading',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('daily_operation', 'pump'), name='unique_pump_reading_per_operation'),
        ),
    ]
