# Generated by Django 6.0.6 on 2026-06-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_dailyoperation_unique_daily_operation_per_station_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['station__name', 'name']},
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='api.station'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', True)), fields=('name',), name='unique_global_expense_category_name'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', False)), fields=('station', 'name'), name='unique_expense_category_name_per_station'),
        ),
    ]
