# Generated by Django 6.0.6 on 2026-06-29 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedTourProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_key', models.CharField(max_length=64)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('dismissed', 'Dismissed')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_tour_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'guide_key', 'version'],
                'constraints': [models.UniqueConstraint(fields=('user', 'guide_key', 'version'), name='unique_user_guided_tour_version')],
            },
        ),
    ]
