name: Basic CI

on:
  push:
    branches:
      - main


jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files
        run: |
          pwd
          ls -la
      
      - name: Test docker compose file exists
        run: |
          test -f compose.yaml
      
      - name: Create .env file
        run: |
          touch .env 


      - name: Validate Compose configuration
        run: |
          docker compose config

      - name: Build docker image
        run: |
          docker compose up

      - name: Shutdown docker compose
        run: |
          docker compose down
      
      